spring:

    application:
        name: prices

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: alvaro
        password:

    jpa:
        database-platform:  org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true
