spring:

    application:
        name: prices

    datasource:
        url: jdbc:h2:mem:testdb;TIME ZONE=UTC
        driverClassName: org.h2.Driver
        username: user
        password:

    jpa:
        database-platform:  org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    
    jackson:
        time-zone: UTC

    h2:
        console:
            enabled: true
